[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # Ensure API base includes /api suffix
  VITE_API_URL = "https://nitzutz-backend-production-423f.up.railway.app/api"
