[build]
  base = "frontend"
  publish = "dist"
  command = "npm ci && npm run build"
  # Always build (don't skip when no detected changes)
  ignore = "false"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"