services:
  - type: web
    name: nitzutz-backend
    runtime: node
    region: frankfurt
    buildCommand: npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: DATABASE_URL
        value: file:./backend/prod.db
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: AI_API_KEY
        sync: false
      - key: AI_BASE_URL
        value: https://router.huggingface.co/v1
      - key: AI_MODEL
        value: deepseek-ai/DeepSeek-V3.2-Exp:novita
