[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run build",
  "npx prisma generate"
]

[start]
cmd = "npx prisma db push --accept-data-loss && npm run start"